//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMobileLoginToken
    {
        public int Id { get; set; }
        public int Aid { get; set; }
        public string Selector { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
