//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.BringAccountItemLogs = new HashSet<BringAccountItemLog>();
            this.CashItemPresentLogs = new HashSet<CashItemPresentLog>();
            this.Characters = new HashSet<Character>();
            this.ItemPurchaseLogByCashes = new HashSet<ItemPurchaseLogByCash>();
            this.SetItemPurchaseLogByCashes = new HashSet<SetItemPurchaseLogByCash>();
            this.AccountItems = new HashSet<AccountItem>();
            this.AccountPenaltyGMLogs = new HashSet<AccountPenaltyGMLog>();
            this.AccountPenaltyLogs = new HashSet<AccountPenaltyLog>();
            this.AccountPenaltyPeriods = new HashSet<AccountPenaltyPeriod>();
            this.AccountMobileLoginTokens = new HashSet<AccountMobileLoginToken>();
            this.CharacterComments = new HashSet<CharacterComment>();
            this.ClanComments = new HashSet<ClanComment>();
            this.DonateShopLogs = new HashSet<DonateShopLog>();
            this.MobileChatContacts = new HashSet<MobileChatContact>();
        }
    
        public int AID { get; set; }
        public string UserID { get; set; }
        public int UGradeID { get; set; }
        public int PGradeID { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string RegNum { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public Nullable<int> LastCID { get; set; }
        public Nullable<byte> Cert { get; set; }
        public Nullable<short> Question { get; set; }
        public string Answer { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EndblockDate { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastLogoutTime { get; set; }
        public Nullable<int> ServerID { get; set; }
        public Nullable<byte> BlockType { get; set; }
        public Nullable<byte> HackingType { get; set; }
        public Nullable<System.DateTime> HackingRegTime { get; set; }
        public Nullable<System.DateTime> EndHackingBlockTime { get; set; }
        public Nullable<byte> IsPowerLevelingHacker { get; set; }
        public Nullable<System.DateTime> PowerLevelingRegDate { get; set; }
        public int DonationCoins { get; set; }
        public int EventCoins { get; set; }
        public string AvatarUrl { get; set; }
        public string PasswordResetCode { get; set; }
        public Nullable<System.DateTime> PasswordResetDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BringAccountItemLog> BringAccountItemLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashItemPresentLog> CashItemPresentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Characters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPurchaseLogByCash> ItemPurchaseLogByCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetItemPurchaseLogByCash> SetItemPurchaseLogByCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountItem> AccountItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPenaltyGMLog> AccountPenaltyGMLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPenaltyLog> AccountPenaltyLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPenaltyPeriod> AccountPenaltyPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMobileLoginToken> AccountMobileLoginTokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterComment> CharacterComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanComment> ClanComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonateShopLog> DonateShopLogs { get; set; }
        public virtual EventAccount EventAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileChatContact> MobileChatContacts { get; set; }
        public virtual PremiumGrade PremiumGrade { get; set; }
        public virtual UserGrade UserGrade { get; set; }
    }
}
