//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPenaltyGMType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountPenaltyGMType()
        {
            this.AccountPenaltyGMLogs = new HashSet<AccountPenaltyGMLog>();
            this.AccountPenaltyGMLogs1 = new HashSet<AccountPenaltyGMLog>();
        }
    
        public byte GM_TypeID { get; set; }
        public string GM_TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPenaltyGMLog> AccountPenaltyGMLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPenaltyGMLog> AccountPenaltyGMLogs1 { get; set; }
    }
}
