//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPenaltyLog
    {
        public int PenaltyLogID { get; set; }
        public Nullable<int> AID { get; set; }
        public Nullable<int> UGradeID { get; set; }
        public Nullable<int> DayLeft { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string GMID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
