//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleTimeRewardDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BattleTimeRewardDescription()
        {
            this.BattleTimeRewardItemLists = new HashSet<BattleTimeRewardItemList>();
            this.BattleTimeRewardTerms = new HashSet<BattleTimeRewardTerm>();
            this.CharacterBattleTimeRewardInfoes = new HashSet<CharacterBattleTimeRewardInfo>();
        }
    
        public int BRID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<byte> StartHour { get; set; }
        public Nullable<byte> EndHour { get; set; }
        public int RewardMinutePeriod { get; set; }
        public byte RewardCount { get; set; }
        public byte RewardKillCount { get; set; }
        public string ResetCode { get; set; }
        public string ResetDesc { get; set; }
        public Nullable<byte> IsOpen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleTimeRewardItemList> BattleTimeRewardItemLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BattleTimeRewardTerm> BattleTimeRewardTerms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CharacterBattleTimeRewardInfo> CharacterBattleTimeRewardInfoes { get; set; }
    }
}
