//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleTimeRewardTerm
    {
        public int BRID { get; set; }
        public int BRTID { get; set; }
        public System.DateTime LastResetDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
    
        public virtual BattleTimeRewardDescription BattleTimeRewardDescription { get; set; }
    }
}
