//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleTimeRewardItemList
    {
        public int BRIID { get; set; }
        public int BRID { get; set; }
        public int ItemIDMale { get; set; }
        public int ItemIDFemale { get; set; }
        public Nullable<int> RentHourPeriod { get; set; }
        public Nullable<int> ItemCnt { get; set; }
        public int RatePerThousand { get; set; }
    
        public virtual BattleTimeRewardDescription BattleTimeRewardDescription { get; set; }
    }
}
