//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSetItem
    {
        public int CSIID { get; set; }
        public int CSSID { get; set; }
        public int CSID { get; set; }
    
        public virtual CashSetShop CashSetShop { get; set; }
        public virtual CashShop CashShop { get; set; }
    }
}
