//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSetShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashSetShop()
        {
            this.CashSetItems = new HashSet<CashSetItem>();
            this.SetItemPurchaseLogByCashes = new HashSet<SetItemPurchaseLogByCash>();
            this.RentCashSetShopPrices = new HashSet<RentCashSetShopPrice>();
        }
    
        public int CSSID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CashPrice { get; set; }
        public string WebImgName { get; set; }
        public Nullable<byte> NewItemOrder { get; set; }
        public Nullable<byte> ResSex { get; set; }
        public Nullable<int> ResLevel { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<byte> Opened { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<byte> RentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashSetItem> CashSetItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetItemPurchaseLogByCash> SetItemPurchaseLogByCashes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentCashSetShopPrice> RentCashSetShopPrices { get; set; }
    }
}
