//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashShop()
        {
            this.CashSetItems = new HashSet<CashSetItem>();
            this.RentCashShopPrices = new HashSet<RentCashShopPrice>();
        }
    
        public int CSID { get; set; }
        public int ItemID { get; set; }
        public Nullable<byte> NewItemOrder { get; set; }
        public int CashPrice { get; set; }
        public string WebImgName { get; set; }
        public Nullable<byte> Opened { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<byte> RentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashSetItem> CashSetItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentCashShopPrice> RentCashShopPrices { get; set; }
    }
}
