//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashShopNewItem
    {
        public int id { get; set; }
        public string Category { get; set; }
        public int NewOrder { get; set; }
        public int IsSetItem { get; set; }
        public Nullable<int> CSID { get; set; }
        public Nullable<int> CSSID { get; set; }
        public string Slot { get; set; }
        public string Name { get; set; }
        public int ResSex { get; set; }
        public int ResLevel { get; set; }
        public int CashPrice { get; set; }
        public string WebImgName { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
