//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_EventItem_X
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsUsed { get; set; }
    }
}
