//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterMgrLogByGM
    {
        public int CharMgrLogID { get; set; }
        public Nullable<int> CID { get; set; }
        public string CharName { get; set; }
        public Nullable<byte> CharMgrTypeID { get; set; }
        public string GMID { get; set; }
        public string NewName { get; set; }
        public Nullable<int> OrgValue { get; set; }
        public Nullable<int> NewValue { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual CharacterMgrType CharacterMgrType { get; set; }
    }
}
