//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterMakingLog
    {
        public int id { get; set; }
        public Nullable<int> AID { get; set; }
        public string CharName { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
