//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterItem
    {
        public int CIID { get; set; }
        public Nullable<int> CID { get; set; }
        public int ItemID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<short> RentHourPeriod { get; set; }
        public Nullable<short> Cnt { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
