//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterEquipmentSlot
    {
        public int CID { get; set; }
        public int SlotID { get; set; }
        public Nullable<int> CIID { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual CharacterEquipmentSlotCode CharacterEquipmentSlotCode { get; set; }
    }
}
