//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterBattleTimeRewardInfo
    {
        public int CID { get; set; }
        public int BRID { get; set; }
        public int BRTID { get; set; }
        public Nullable<int> BattleTime { get; set; }
        public Nullable<int> RewardCount { get; set; }
        public Nullable<int> KillCount { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual BattleTimeRewardDescription BattleTimeRewardDescription { get; set; }
    }
}
