//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clan()
        {
            this.ClanGameLogs = new HashSet<ClanGameLog>();
            this.ClanGameLogs1 = new HashSet<ClanGameLog>();
            this.ClanHonorRankings = new HashSet<ClanHonorRanking>();
            this.ClanMembers = new HashSet<ClanMember>();
            this.ClanComments = new HashSet<ClanComment>();
        }
    
        public int CLID { get; set; }
        public string Name { get; set; }
        public int Exp { get; set; }
        public byte Level { get; set; }
        public int Point { get; set; }
        public Nullable<int> MasterCID { get; set; }
        public int Wins { get; set; }
        public string MarkWebImg { get; set; }
        public string Introduction { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<byte> DeleteFlag { get; set; }
        public string DeleteName { get; set; }
        public string Homepage { get; set; }
        public int Losses { get; set; }
        public int Draws { get; set; }
        public int Ranking { get; set; }
        public int TotalPoint { get; set; }
        public string Cafe_Url { get; set; }
        public string Email { get; set; }
        public string EmblemUrl { get; set; }
        public int RankIncrease { get; set; }
        public int EmblemChecksum { get; set; }
        public int LastDayRanking { get; set; }
        public int LastMonthRanking { get; set; }
        public string Password { get; set; }
        public string HeaderUrl { get; set; }
        public string FaceBookUrl { get; set; }
        public string GooglePlusUrl { get; set; }
        public string TwitterUrl { get; set; }
    
        public virtual Character Character { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanGameLog> ClanGameLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanGameLog> ClanGameLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanHonorRanking> ClanHonorRankings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanMember> ClanMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanComment> ClanComments { get; set; }
    }
}
