//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanHonorRanking
    {
        public int id { get; set; }
        public Nullable<int> CLID { get; set; }
        public string ClanName { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public int RankIncrease { get; set; }
    
        public virtual Clan Clan { get; set; }
    }
}
