//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanGameLog
    {
        public int id { get; set; }
        public int WinnerCLID { get; set; }
        public int LoserCLID { get; set; }
        public string WinnerClanName { get; set; }
        public string LoserClanName { get; set; }
        public string WinnerMembers { get; set; }
        public string LoserMembers { get; set; }
        public byte RoundWins { get; set; }
        public byte RoundLosses { get; set; }
        public byte MapID { get; set; }
        public byte GameType { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<int> WinnerPoint { get; set; }
        public Nullable<int> LoserPoint { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual Clan Clan1 { get; set; }
    }
}
