//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanAdsBoard
    {
        public int Seq { get; set; }
        public string UserID { get; set; }
        public string Subject { get; set; }
        public System.DateTime RegDate { get; set; }
        public int ReadCount { get; set; }
        public Nullable<int> Recommend { get; set; }
        public string Content { get; set; }
        public string FileName { get; set; }
        public string Link { get; set; }
        public short HTML { get; set; }
        public int CommentCount { get; set; }
        public int GR_ID { get; set; }
        public int GR_Depth { get; set; }
        public int GR_Pos { get; set; }
        public int Thread { get; set; }
    }
}
