//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomIP
    {
        public long IPFrom { get; set; }
        public long IPTo { get; set; }
        public byte IsBlock { get; set; }
        public string CountryCode3 { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    }
}
