//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GunzDBEntities : DbContext
    {
        public GunzDBEntities()
            : base("name=GunzDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbuseList> AbuseLists { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountItem> AccountItems { get; set; }
        public virtual DbSet<AccountMobileLoginToken> AccountMobileLoginTokens { get; set; }
        public virtual DbSet<AccountPenaltyCode> AccountPenaltyCodes { get; set; }
        public virtual DbSet<AccountPenaltyGMLog> AccountPenaltyGMLogs { get; set; }
        public virtual DbSet<AccountPenaltyGMType> AccountPenaltyGMTypes { get; set; }
        public virtual DbSet<AccountPenaltyLog> AccountPenaltyLogs { get; set; }
        public virtual DbSet<AccountPenaltyPeriod> AccountPenaltyPeriods { get; set; }
        public virtual DbSet<BattleTimeRewardDescription> BattleTimeRewardDescriptions { get; set; }
        public virtual DbSet<BattleTimeRewardItemList> BattleTimeRewardItemLists { get; set; }
        public virtual DbSet<BattleTimeRewardTerm> BattleTimeRewardTerms { get; set; }
        public virtual DbSet<BillingMethod> BillingMethods { get; set; }
        public virtual DbSet<BlockCountryCode> BlockCountryCodes { get; set; }
        public virtual DbSet<BringAccountItemLog> BringAccountItemLogs { get; set; }
        public virtual DbSet<CashItemPresentLog> CashItemPresentLogs { get; set; }
        public virtual DbSet<CashSetItem> CashSetItems { get; set; }
        public virtual DbSet<CashSetShop> CashSetShops { get; set; }
        public virtual DbSet<CashShop> CashShops { get; set; }
        public virtual DbSet<CashShopNewItemCategory> CashShopNewItemCategories { get; set; }
        public virtual DbSet<CashShopRank> CashShopRanks { get; set; }
        public virtual DbSet<CB_EventItem> CB_EventItem { get; set; }
        public virtual DbSet<CB_EventItem_X> CB_EventItem_X { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<CharacterBattleTimeRewardInfo> CharacterBattleTimeRewardInfoes { get; set; }
        public virtual DbSet<CharacterComment> CharacterComments { get; set; }
        public virtual DbSet<CharacterEquipmentSlot> CharacterEquipmentSlots { get; set; }
        public virtual DbSet<CharacterEquipmentSlotCode> CharacterEquipmentSlotCodes { get; set; }
        public virtual DbSet<CharacterItem> CharacterItems { get; set; }
        public virtual DbSet<CharacterMgrLogByGM> CharacterMgrLogByGMs { get; set; }
        public virtual DbSet<CharacterMgrType> CharacterMgrTypes { get; set; }
        public virtual DbSet<CharacterSkill> CharacterSkills { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<ClanAdsBoard> ClanAdsBoards { get; set; }
        public virtual DbSet<ClanComment> ClanComments { get; set; }
        public virtual DbSet<ClanGameLog> ClanGameLogs { get; set; }
        public virtual DbSet<ClanHonorRanking> ClanHonorRankings { get; set; }
        public virtual DbSet<ClanMember> ClanMembers { get; set; }
        public virtual DbSet<ClanMemberGrade> ClanMemberGrades { get; set; }
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<DayRanking> DayRankings { get; set; }
        public virtual DbSet<DonateShopLog> DonateShopLogs { get; set; }
        public virtual DbSet<DonatorDailyItem> DonatorDailyItems { get; set; }
        public virtual DbSet<DonatorDailyItemLog> DonatorDailyItemLogs { get; set; }
        public virtual DbSet<DonatorShopCategory> DonatorShopCategories { get; set; }
        public virtual DbSet<DonatorShopItem> DonatorShopItems { get; set; }
        public virtual DbSet<DonatorShopSetItem> DonatorShopSetItems { get; set; }
        public virtual DbSet<DTCharacterInfo> DTCharacterInfoes { get; set; }
        public virtual DbSet<DTCharacterRanking> DTCharacterRankings { get; set; }
        public virtual DbSet<DTCharacterRankingHistory> DTCharacterRankingHistories { get; set; }
        public virtual DbSet<DTGameLog> DTGameLogs { get; set; }
        public virtual DbSet<DTGameLogDetail> DTGameLogDetails { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<DTTimeStamp> DTTimeStamps { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Event_Coliseum_Character_NHN> Event_Coliseum_Character_NHN { get; set; }
        public virtual DbSet<Event_Coliseum_DeathsRanking_NHN> Event_Coliseum_DeathsRanking_NHN { get; set; }
        public virtual DbSet<Event_Coliseum_KillsRanking_NHN> Event_Coliseum_KillsRanking_NHN { get; set; }
        public virtual DbSet<Event_Coliseum_PlayData_NHN> Event_Coliseum_PlayData_NHN { get; set; }
        public virtual DbSet<Event_Coliseum_PlayTimeRanking_NHN> Event_Coliseum_PlayTimeRanking_NHN { get; set; }
        public virtual DbSet<event_easter2011> event_easter2011 { get; set; }
        public virtual DbSet<Event_MDTCharacter> Event_MDTCharacter { get; set; }
        public virtual DbSet<Event_MDTCharacterRankingHistory> Event_MDTCharacterRankingHistory { get; set; }
        public virtual DbSet<Event_Word_NHN> Event_Word_NHN { get; set; }
        public virtual DbSet<EventAccount> EventAccounts { get; set; }
        public virtual DbSet<EventCharacter> EventCharacters { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<GambleItem> GambleItems { get; set; }
        public virtual DbSet<GambleRewardItem> GambleRewardItems { get; set; }
        public virtual DbSet<GameType> GameTypes { get; set; }
        public virtual DbSet<Ignore> Ignores { get; set; }
        public virtual DbSet<IPtoCountry> IPtoCountries { get; set; }
        public virtual DbSet<IPtoCountry_temp> IPtoCountry_temp { get; set; }
        public virtual DbSet<ItemChangeLog_AccountItem> ItemChangeLog_AccountItem { get; set; }
        public virtual DbSet<ItemChangeType> ItemChangeTypes { get; set; }
        public virtual DbSet<ItemSlotType> ItemSlotTypes { get; set; }
        public virtual DbSet<KillLog> KillLogs { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LevelUpLog> LevelUpLogs { get; set; }
        public virtual DbSet<LocatorStatu> LocatorStatus { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MobileChat> MobileChats { get; set; }
        public virtual DbSet<MobileChatContact> MobileChatContacts { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NHNClanMark> NHNClanMarks { get; set; }
        public virtual DbSet<NHNItemOfTheDay> NHNItemOfTheDays { get; set; }
        public virtual DbSet<NHNItemOfTheDayLog> NHNItemOfTheDayLogs { get; set; }
        public virtual DbSet<NHNPurchaseLog> NHNPurchaseLogs { get; set; }
        public virtual DbSet<NHNRareItemShop> NHNRareItemShops { get; set; }
        public virtual DbSet<NHNRareItemShopLog> NHNRareItemShopLogs { get; set; }
        public virtual DbSet<Paypal> Paypals { get; set; }
        public virtual DbSet<PaypalPaymentOption> PaypalPaymentOptions { get; set; }
        public virtual DbSet<PenaltyLog> PenaltyLogs { get; set; }
        public virtual DbSet<PremiumGrade> PremiumGrades { get; set; }
        public virtual DbSet<PurchaseMethod> PurchaseMethods { get; set; }
        public virtual DbSet<QuestGameLog> QuestGameLogs { get; set; }
        public virtual DbSet<QuestItem> QuestItems { get; set; }
        public virtual DbSet<QUniqueItemLog> QUniqueItemLogs { get; set; }
        public virtual DbSet<RentCashSetShopPrice> RentCashSetShopPrices { get; set; }
        public virtual DbSet<RentCashShopPrice> RentCashShopPrices { get; set; }
        public virtual DbSet<RentPeriodDay> RentPeriodDays { get; set; }
        public virtual DbSet<RentType> RentTypes { get; set; }
        public virtual DbSet<ServerLogStorage> ServerLogStorages { get; set; }
        public virtual DbSet<ServerStatu> ServerStatus { get; set; }
        public virtual DbSet<ServerType> ServerTypes { get; set; }
        public virtual DbSet<SleepAccountNHN> SleepAccountNHNs { get; set; }
        public virtual DbSet<SleepAccountRestoredLogNHN> SleepAccountRestoredLogNHNs { get; set; }
        public virtual DbSet<SleepCharacterNHN> SleepCharacterNHNs { get; set; }
        public virtual DbSet<SleepCharacterRestoredLogNHN> SleepCharacterRestoredLogNHNs { get; set; }
        public virtual DbSet<SurvivalCharacterInfo> SurvivalCharacterInfoes { get; set; }
        public virtual DbSet<SurvivalCharacterInfoWeb> SurvivalCharacterInfoWebs { get; set; }
        public virtual DbSet<SurvivalGameLog> SurvivalGameLogs { get; set; }
        public virtual DbSet<SurvivalRanking> SurvivalRankings { get; set; }
        public virtual DbSet<SurvivalScenarioID> SurvivalScenarioIDs { get; set; }
        public virtual DbSet<tmp_summerwave_newreg_event> tmp_summerwave_newreg_event { get; set; }
        public virtual DbSet<tmp_summerwave_raffle_event> tmp_summerwave_raffle_event { get; set; }
        public virtual DbSet<TotalRanking> TotalRankings { get; set; }
        public virtual DbSet<UserGrade> UserGrades { get; set; }
        public virtual DbSet<UV> UVs { get; set; }
        public virtual DbSet<CashSetItemDetail> CashSetItemDetails { get; set; }
        public virtual DbSet<CashShopNewItem> CashShopNewItems { get; set; }
        public virtual DbSet<CharacterBattleTimeRewardLog> CharacterBattleTimeRewardLogs { get; set; }
        public virtual DbSet<CharacterMakingLog> CharacterMakingLogs { get; set; }
        public virtual DbSet<CustomIP> CustomIPs { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Event_CharacterItem_Halloween> Event_CharacterItem_Halloween { get; set; }
        public virtual DbSet<Event_ClanPointRanking> Event_ClanPointRanking { get; set; }
        public virtual DbSet<GameLog> GameLogs { get; set; }
        public virtual DbSet<ipto_back> ipto_back { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemChangeLog_CharacterItem> ItemChangeLog_CharacterItem { get; set; }
        public virtual DbSet<ItemDetail> ItemDetails { get; set; }
        public virtual DbSet<ItemPurchaseLogByBounty> ItemPurchaseLogByBounties { get; set; }
        public virtual DbSet<ItemPurchaseLogByCash> ItemPurchaseLogByCashes { get; set; }
        public virtual DbSet<NHNLuckyBoxCoupon> NHNLuckyBoxCoupons { get; set; }
        public virtual DbSet<NHNLuckyBoxInventory> NHNLuckyBoxInventories { get; set; }
        public virtual DbSet<NHNLuckyBoxItem> NHNLuckyBoxItems { get; set; }
        public virtual DbSet<NHNLuckyBoxRewardItem> NHNLuckyBoxRewardItems { get; set; }
        public virtual DbSet<PlayerLog> PlayerLogs { get; set; }
        public virtual DbSet<ServerLog> ServerLogs { get; set; }
        public virtual DbSet<SetItemPurchaseLogByCash> SetItemPurchaseLogByCashes { get; set; }
        public virtual DbSet<tmp_stampevent> tmp_stampevent { get; set; }
        public virtual DbSet<ItemRotation> ItemRotations { get; set; }
    }
}
