//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayRanking
    {
        public int id { get; set; }
        public string Name { get; set; }
        public short Level { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Rank { get; set; }
    }
}
