//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonatorShopItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonatorShopItem()
        {
            this.DonatorShopSetItems = new HashSet<DonatorShopSetItem>();
            this.DonatorShopSetItems1 = new HashSet<DonatorShopSetItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime Date { get; set; }
        public string Image { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public int Damage { get; set; }
        public int Delay { get; set; }
        public int Magazine { get; set; }
        public int MaxBullet { get; set; }
        public int MaxWeight { get; set; }
        public int ReloadTime { get; set; }
        public int Hp { get; set; }
        public int Ap { get; set; }
        public Nullable<int> Sex { get; set; }
        public int Weight { get; set; }
        public int DailyPrice { get; set; }
        public Nullable<int> NewDailyPrice { get; set; }
        public Nullable<int> ForeverPrice { get; set; }
        public Nullable<int> NewForeverPrice { get; set; }
    
        public virtual DonatorShopCategory DonatorShopCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonatorShopSetItem> DonatorShopSetItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonatorShopSetItem> DonatorShopSetItems1 { get; set; }
    }
}
