//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTCharacterInfo
    {
        public int DTCIID { get; set; }
        public string TimeStamp { get; set; }
        public int CID { get; set; }
        public int TP { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Ranking { get; set; }
        public int RankingIncrease { get; set; }
        public int FinalGames { get; set; }
        public int FinalWins { get; set; }
        public int SFinalGames { get; set; }
        public int SFinalWins { get; set; }
        public int QFinalGames { get; set; }
        public int QFinalWins { get; set; }
        public int LeaveCount { get; set; }
        public int PreGrade { get; set; }
    }
}
