//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTGameLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DTGameLog()
        {
            this.DTGameLogDetails = new HashSet<DTGameLogDetail>();
        }
    
        public string TimeStamp { get; set; }
        public int LogID { get; set; }
        public byte TournamentType { get; set; }
        public Nullable<int> ChampCID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<byte> MatchFactor { get; set; }
        public Nullable<int> Player1CID { get; set; }
        public Nullable<int> Player2CID { get; set; }
        public Nullable<int> Player3CID { get; set; }
        public Nullable<int> Player4CID { get; set; }
        public Nullable<int> Player5CID { get; set; }
        public Nullable<int> Player6CID { get; set; }
        public Nullable<int> Player7CID { get; set; }
        public Nullable<int> Player8CID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTGameLogDetail> DTGameLogDetails { get; set; }
        public virtual DTTimeStamp DTTimeStamp { get; set; }
    }
}
