//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effect
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> ModHP { get; set; }
        public Nullable<int> ModAP { get; set; }
        public Nullable<int> ModMaxWT { get; set; }
        public Nullable<int> ModSF { get; set; }
        public Nullable<int> ModFR { get; set; }
        public Nullable<int> ModCR { get; set; }
        public Nullable<int> ModPR { get; set; }
        public Nullable<int> ModLR { get; set; }
        public Nullable<int> ResAP { get; set; }
        public Nullable<int> ResFR { get; set; }
        public Nullable<int> ResCR { get; set; }
        public Nullable<int> ResPR { get; set; }
        public Nullable<int> ResLR { get; set; }
        public Nullable<int> Stun { get; set; }
        public Nullable<int> KnockBack { get; set; }
        public Nullable<int> Smoke { get; set; }
        public Nullable<int> Flash { get; set; }
        public Nullable<int> Tear { get; set; }
        public Nullable<int> Flame { get; set; }
    }
}
