//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Coliseum_PlayData_NHN
    {
        public string DateTag { get; set; }
        public int CID { get; set; }
        public int PlayTime { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<int> PlayTimeRank { get; set; }
        public Nullable<int> KillRank { get; set; }
        public Nullable<int> DeathRank { get; set; }
    
        public virtual Event_Coliseum_Character_NHN Event_Coliseum_Character_NHN { get; set; }
    }
}
