//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Word_NHN
    {
        public int CID { get; set; }
        public Nullable<short> Have_A { get; set; }
        public Nullable<short> Happy { get; set; }
        public Nullable<short> Halloween { get; set; }
        public Nullable<short> From { get; set; }
        public Nullable<short> IJJI { get; set; }
        public Nullable<short> AND { get; set; }
        public Nullable<short> MAIET_ { get; set; }
        public Nullable<short> Pumpkin { get; set; }
        public Nullable<short> Ghost { get; set; }
        public Nullable<short> Trick_Or { get; set; }
        public Nullable<short> Treat__ { get; set; }
    }
}
