//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventAccount()
        {
            this.EventCharacters = new HashSet<EventCharacter>();
        }
    
        public int AID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> XPOrder { get; set; }
        public Nullable<int> LevelOrder { get; set; }
        public Nullable<int> PlayTimeOrder { get; set; }
        public int GainXP { get; set; }
        public int GainLevel { get; set; }
        public int GainPlayTime { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventCharacter> EventCharacters { get; set; }
    }
}
