//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_CharacterItem_Halloween
    {
        public string UserID { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> Trick { get; set; }
        public Nullable<int> Treat { get; set; }
    }
}
