//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCharacter
    {
        public int AID { get; set; }
        public int CID { get; set; }
        public bool DeleteFlag { get; set; }
        public int StartXP { get; set; }
        public int StartLevel { get; set; }
        public Nullable<int> PlayTime { get; set; }
        public int LastXP { get; set; }
        public int LastLevel { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual EventAccount EventAccount { get; set; }
    }
}
