//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_ClanPointRanking
    {
        public int id { get; set; }
        public int Rank { get; set; }
        public int CLID { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int Point { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
