//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_MDTCharacterRankingHistory
    {
        public string TimeStamp { get; set; }
        public int Rank { get; set; }
        public int CID { get; set; }
        public int TP { get; set; }
        public int FinalWins { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Grade { get; set; }
    }
}
