//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Coliseum_Character_NHN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_Coliseum_Character_NHN()
        {
            this.Event_Coliseum_PlayData_NHN = new HashSet<Event_Coliseum_PlayData_NHN>();
        }
    
        public int CID { get; set; }
        public System.DateTime RegDate { get; set; }
    
        public virtual Character Character { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event_Coliseum_PlayData_NHN> Event_Coliseum_PlayData_NHN { get; set; }
    }
}
