//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GambleItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GambleItem()
        {
            this.GambleRewardItems = new HashSet<GambleRewardItem>();
        }
    
        public int GIID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public short LifeTimeHour { get; set; }
        public byte IsCash { get; set; }
        public byte Opened { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GambleRewardItem> GambleRewardItems { get; set; }
    }
}
