//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GambleRewardItem
    {
        public int GRIID { get; set; }
        public int GIID { get; set; }
        public int ItemIDMale { get; set; }
        public int ItemIDFemale { get; set; }
        public int RentHourPeriod { get; set; }
        public short RatePerThousand { get; set; }
    
        public virtual GambleItem GambleItem { get; set; }
    }
}
