//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameLog
    {
        public int id { get; set; }
        public string GameName { get; set; }
        public Nullable<int> MasterCID { get; set; }
        public string Map { get; set; }
        public string GameType { get; set; }
        public Nullable<int> Round { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<byte> PlayerCount { get; set; }
        public string Players { get; set; }
    }
}
