//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalPoint { get; set; }
        public Nullable<byte> ResSex { get; set; }
        public Nullable<byte> ResRace { get; set; }
        public Nullable<int> ResLevel { get; set; }
        public Nullable<byte> Slot { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> BountyPrice { get; set; }
        public Nullable<int> Damage { get; set; }
        public Nullable<int> Delay { get; set; }
        public Nullable<int> EffectID { get; set; }
        public Nullable<int> Controllability { get; set; }
        public Nullable<int> Magazine { get; set; }
        public Nullable<int> ReloadTime { get; set; }
        public Nullable<byte> SlugOutput { get; set; }
        public Nullable<int> Gadget { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> AP { get; set; }
        public Nullable<int> MAXWT { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> FR { get; set; }
        public Nullable<int> CR { get; set; }
        public Nullable<int> PR { get; set; }
        public Nullable<int> LR { get; set; }
        public Nullable<int> BlendColor { get; set; }
        public string ModelName { get; set; }
        public string Description { get; set; }
        public Nullable<int> MaxBullet { get; set; }
        public Nullable<byte> LimitSpeed { get; set; }
        public Nullable<byte> IsCashItem { get; set; }
        public Nullable<byte> IsSpendableItem { get; set; }
    }
}
