//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemChangeLog_CharacterItem
    {
        public System.DateTime ChangeDate { get; set; }
        public short ChangeType { get; set; }
        public int LogID { get; set; }
        public int CID { get; set; }
        public int CIID { get; set; }
        public Nullable<int> AID { get; set; }
        public Nullable<int> AIID { get; set; }
        public int ItemID { get; set; }
        public int Count { get; set; }
    }
}
