//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPurchaseLogByBounty
    {
        public int id { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Bounty { get; set; }
        public Nullable<int> CharBounty { get; set; }
        public string Type { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
