//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPurchaseLogByCash
    {
        public int id { get; set; }
        public Nullable<int> AID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> RentHourPeriod { get; set; }
        public string MobileCode { get; set; }
        public string sid { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
