//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelUpLog
    {
        public int id { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<short> Level { get; set; }
        public Nullable<int> BP { get; set; }
        public Nullable<int> KillCount { get; set; }
        public Nullable<int> DeathCount { get; set; }
        public Nullable<int> PlayTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
