//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocatorStatu
    {
        public int LocatorID { get; set; }
        public string IP { get; set; }
        public int Port { get; set; }
        public Nullable<int> RecvCount { get; set; }
        public Nullable<int> SendCount { get; set; }
        public Nullable<int> BlockCount { get; set; }
        public Nullable<int> DuplicatedCount { get; set; }
        public int UpdateElapsedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
