//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNClanMark
    {
        public int CLMARKID { get; set; }
        public int CLID { get; set; }
        public string EmblemUrl { get; set; }
        public Nullable<byte> Approved { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<int> LastCount { get; set; }
        public Nullable<System.DateTime> LastCreated { get; set; }
    }
}
