//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNItemOfTheDay
    {
        public int id { get; set; }
        public string name { get; set; }
        public string itemids { get; set; }
        public byte isset { get; set; }
        public int originalprice { get; set; }
        public Nullable<int> originalperiod { get; set; }
        public Nullable<int> reslevel { get; set; }
        public int price { get; set; }
        public Nullable<int> period { get; set; }
        public int remaining { get; set; }
        public string imgurl { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
