//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNLuckyBoxRewardItem
    {
        public int BoxRID { get; set; }
        public int BoxID { get; set; }
        public string ItemIDs { get; set; }
        public string Name { get; set; }
        public byte Category { get; set; }
        public int RentHourPeriod { get; set; }
        public short RatePerThousand { get; set; }
    }
}
