//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNLuckyBoxCoupon
    {
        public int BoxCID { get; set; }
        public string UserID { get; set; }
        public byte BoxCategory { get; set; }
        public byte Status { get; set; }
        public Nullable<int> BoxID { get; set; }
        public string sid { get; set; }
        public System.DateTime Regdate { get; set; }
        public Nullable<System.DateTime> Opendate { get; set; }
        public Nullable<System.DateTime> Expiredate { get; set; }
    }
}
