//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNLuckyBoxItem
    {
        public int BoxID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Category { get; set; }
        public string webimgname { get; set; }
        public int Price { get; set; }
        public int RefundPrice { get; set; }
        public byte ResSex { get; set; }
        public short ResLevel { get; set; }
        public byte Opened { get; set; }
        public int displayorder { get; set; }
        public System.DateTime Regdate { get; set; }
    }
}
