//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNLuckyBoxInventory
    {
        public int BoxIID { get; set; }
        public string UserID { get; set; }
        public int BoxID { get; set; }
        public byte Status { get; set; }
        public Nullable<int> BoxRID { get; set; }
        public Nullable<int> RefundPrice { get; set; }
        public string sid { get; set; }
        public string Sender { get; set; }
        public System.DateTime Regdate { get; set; }
    }
}
