//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNPurchaseLog
    {
        public int PID { get; set; }
        public string PurchasedMonth { get; set; }
        public string UserID { get; set; }
        public string PurchasedId { get; set; }
        public Nullable<int> Price { get; set; }
        public string sid { get; set; }
        public Nullable<byte> gift { get; set; }
        public System.DateTime Regdate { get; set; }
    }
}
