//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHNRareItemShop
    {
        public int id { get; set; }
        public string Month { get; set; }
        public string name { get; set; }
        public string itemids { get; set; }
        public byte isset { get; set; }
        public string Type { get; set; }
        public string ResSex { get; set; }
        public Nullable<int> ResLevel { get; set; }
        public int price { get; set; }
        public int period { get; set; }
        public string imgurl { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
