//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paypal
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string InvoiceId { get; set; }
        public string PayerId { get; set; }
        public string PaymentId { get; set; }
        public string Token { get; set; }
        public int PaymentOptionId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    }
}
