//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerLog
    {
        public int id { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<System.DateTime> DisTime { get; set; }
        public Nullable<int> PlayTime { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<int> XP { get; set; }
        public Nullable<int> TotalXP { get; set; }
    }
}
