//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUniqueItemLog
    {
        public int QUILID { get; set; }
        public Nullable<int> QGLID { get; set; }
        public int CID { get; set; }
        public int QIID { get; set; }
    }
}
