//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentCashShopPrice
    {
        public int RCSPID { get; set; }
        public Nullable<int> CSID { get; set; }
        public Nullable<short> RentHourPeriod { get; set; }
        public Nullable<int> CashPrice { get; set; }
    
        public virtual CashShop CashShop { get; set; }
    }
}
