//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerStatu
    {
        public int ServerID { get; set; }
        public Nullable<short> CurrPlayer { get; set; }
        public Nullable<short> MaxPlayer { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public string ServerName { get; set; }
        public Nullable<byte> Opened { get; set; }
        public Nullable<int> Type { get; set; }
        public string AgentIP { get; set; }
    }
}
