//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerLog
    {
        public int id { get; set; }
        public Nullable<short> ServerID { get; set; }
        public Nullable<short> PlayerCount { get; set; }
        public Nullable<short> GameCount { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> BlockCount { get; set; }
        public Nullable<int> NonBlockCount { get; set; }
    }
}
