//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerLogStorage
    {
        public int id { get; set; }
        public short ServerID { get; set; }
        public int PlayerCount { get; set; }
        public int GameCount { get; set; }
        public int BlockCount { get; set; }
        public int NonBlockCount { get; set; }
        public System.DateTime Time { get; set; }
    }
}
