//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepCharacterRestoredLogNHN
    {
        public int CID { get; set; }
        public string OrginName { get; set; }
        public string RestoreName { get; set; }
        public System.DateTime RegDt { get; set; }
        public System.DateTime RestoredDt { get; set; }
    }
}
