//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurvivalCharacterInfo
    {
        public byte SID { get; set; }
        public int CID { get; set; }
        public int RP { get; set; }
        public System.DateTime RP_LatestTime { get; set; }
        public Nullable<int> tmpRP { get; set; }
        public Nullable<int> RankRP { get; set; }
    
        public virtual SurvivalScenarioID SurvivalScenarioID { get; set; }
    }
}
