//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_summerwave_raffle_event
    {
        public string sdate { get; set; }
        public string userid { get; set; }
        public int playtime { get; set; }
        public int gifttype { get; set; }
        public Nullable<System.DateTime> giftdate { get; set; }
    }
}
