//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_stampevent
    {
        public string sdate { get; set; }
        public string UserID { get; set; }
        public int PlayTime { get; set; }
        public Nullable<System.DateTime> GiftDate { get; set; }
    }
}
